### ISSUE TITLE
Unable to configure DbProfileService as authenticator

### ISSUE THREAD

**Issue by htamas** [pac4j/dropwizard-pac4j#33]
I have been trying to configure the DB authenticator with a CookieClient, like this:
```
  clients:
      - org.pac4j.http.client.direct.CookieClient:
          cookieName: "demo"
          authenticator:
           class: org.pac4j.sql.profile.service.DbProfileService
```

But the application fails to start and shows this error message:

> demo-config.yml has an error:
>   * Failed to parse configuration at: pac4j.clients.[0].authenticator; Failed to load class 'javax.sql.DataSource$Access4JacksonDeserializerc5504170': com.fasterxml.jackson.module.afterburner.deser.BeanPropertyMutator
>  at [Source: N/A; line: -1, column: -1] (through reference chain: org.pac4j.demo.dw.Pac4JDemoConfiguration["pac4j"]->org.pac4j.dropwizard.Pac4jFactory["clients"]->java.util.ArrayList[0]->org.pac4j.http.client.direct.CookieClient["authenticator"])
