### ISSUE TITLE
Not redirecting to IDP

### ISSUE THREAD

**Issue by muliyul** [pac4j/dropwizard-pac4j#503]
`GET`ting the `/auth/profile` endpoint yields 401.

Config:
```yaml
pac4j:
  callbackUrl: /auth/callback

  globalFilters:
    - matchers: excludeCallback
      authorizers: isAuthenticated

  matchers:
    excludeCallback:
      class: org.pac4j.core.matching.matcher.PathMatcher
      excludedPath: /auth/callback

  defaultSecurityClients: GoogleOidClient

  clientsProperties:
    oidc.type: google
    oidc.id: ***
    oidc.secret: ***
    oidc.scope: openid email profile
```

Code:
```kotlin
@GET
@Path("/profile")
@Pac4JSecurity(clients = ["GoogleOidClient"])
fun profile(@Pac4JProfile user: CommonProfile) = user
```

Logs:
> DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.engine.DefaultSecurityLogic: === SECURITY ===
DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.engine.DefaultSecurityLogic: url: http://localhost:3000/api/auth/profile
DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.engine.DefaultSecurityLogic: clients: GoogleOidClient | matchers: 
DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.client.finder.DefaultSecurityClientFinder: Provided clientNames: GoogleOidClient
DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.client.finder.DefaultSecurityClientFinder: clientNameOnRequest: Optional.empty
DEBUG [2024-08-16 02:07:55,123] org.pac4j.core.util.InitializableObject: Initializing: Clients (nb: 0, last: null)
DEBUG [2024-08-16 02:07:55,124] org.pac4j.core.client.Clients: Found client: null for name: GoogleOidClient
DEBUG [2024-08-16 02:07:55,124] org.pac4j.core.client.finder.DefaultSecurityClientFinder: result: []
DEBUG [2024-08-16 02:07:55,124] org.pac4j.core.engine.DefaultSecurityLogic: currentClients: []
DEBUG [2024-08-16 02:07:55,132] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #CacheControlMatcher# | -> true
DEBUG [2024-08-16 02:07:55,132] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #XContentTypeOptionsMatcher# | -> true
DEBUG [2024-08-16 02:07:55,133] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #StrictTransportSecurityMatcher# | maxAge: 15768000 | -> true
DEBUG [2024-08-16 02:07:55,133] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #XFrameOptionsMatcher# | -> true
DEBUG [2024-08-16 02:07:55,133] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #XSSProtectionMatcher# | -> true
DEBUG [2024-08-16 02:07:55,133] org.pac4j.core.matching.matcher.csrf.DefaultCsrfTokenGenerator: generated CSRF token: 771608c2207a434a839b2bf6d1869cfe for current URL: http://localhost:3000/api/auth/profile
DEBUG [2024-08-16 02:07:55,134] org.pac4j.core.matching.checker.DefaultMatchingChecker: Checking matcher: #CsrfTokenGeneratorMatcher# | csrfTokenGenerator: org.pac4j.core.matching.matcher.csrf.DefaultCsrfTokenGenerator@4ee462da | domain: null | path: / | httpOnly: true | secure: true | maxAge: null | addTokenAsAttribute: true | addTokenAsHeader: false | addTokenAsCookie: true | -> true
DEBUG [2024-08-16 02:07:55,135] org.pac4j.core.engine.DefaultSecurityLogic: Loaded profiles (from session: true): [] 
DEBUG [2024-08-16 02:07:55,135] org.pac4j.core.engine.DefaultSecurityLogic: unauthorized
[0:0:0:0:0:0:0:1] - - [16/Aug/2024:02:07:55 +0000] "GET /api/auth/profile HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" 93

Probably a misconfiguration or a misunderstanding but dropwizard documentation is (kind of) lacking...
